on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    name: "Release Please"
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
      version: ${{ steps.release-please.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: |
          echo "Version: ${{ steps.release-please.outputs.version }}"
          echo "Release Created: ${{ steps.release-please.outputs.release_created }}"
          echo "Tag Name: ${{ steps.release-please.outputs.tag_name }}"
  build-and-release:
    needs: release-please
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [win-x64, win-arm64]
        self-contained: [true, false]
    name: "Build ${{ matrix.runtime }} Self-Contained: ${{ matrix.self-contained }}"
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo "Version: ${{ needs.release-please.outputs.version }}"
          echo "Release Created: ${{ needs.release-please.outputs.release_created }}"
          echo "Tag Name: ${{ needs.release-please.outputs.tag_name }}"

      - name: Build
        if: ${{ needs.release-please.outputs.release_created || (matrix.runtime == 'win-x64' && matrix.self-contained == false) }}
        uses: ./.github/actions/build
        with:
          runtime: ${{ matrix.runtime }}
          self-contained: ${{ matrix.self-contained }}
          version: ${{ needs.release-please.outputs.version }}
      
      - uses: actions/download-artifact@v4
        if: ${{ needs.release-please.outputs.release_created || (matrix.runtime == 'win-x64' && matrix.self-contained == false) }}
        with:
          name: "thirds-for-windows11-${{ matrix.runtime }}-self-contained-${{ matrix.self-contained }}"
          path: "./test-publish/${{ matrix.runtime }}.self-contained-${{ matrix.self-contained }}"

      - name: Upload Release Artifact
        shell: pwsh
        if: ${{ needs.release-please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} ./test-publish/${{ matrix.runtime }}.self-contained-${{ matrix.self-contained }}/thirds-for-windows11.exe
